### ISSUE TITLE
Intercept http status codes

### ISSUE THREAD

**Issue by Billybob** [crissdev/spa-template-ko#1]
Hi,
I would like to intercept the 401 status code and redirect to a login page. An idea on how to do?
thanks

**Comment by crissdev** [comment]
Hi Mickael

You need to add an interceptor for `responseError`. Here's an example:

``` js
var $http = require('$http');
var q = require('q');

$http.interceptors.push({
    responseError: function(rejection) {
        if (rejection.status === 401) {
            return q.reject(new Error('You are not authorized.'));
        }
        return rejection;
    }
});
```

**Comment by Billybob** [comment]
Great! Thank you very much for the quick answer

Still about $http, how to pass parameters to moduleConfig.headers (eg Authorization' token)?

**Comment by crissdev** [comment]
`moduleConfig` comes from the standard way of defining configuration for a module in RequireJS. You can read more about that [here](http://requirejs.org/docs/api.html#config-moduleconfig).

In your case you would have to add something like this to your RequireJS configuration:

``` js
requirejs.config({
    //...
    config: {
        'app/application': {
            modules: [
                //-inject:modules
                //-end-inject
            ]
        },
        // Using $http (the alias) here will not work!!
        'app/shared/http': {
            headers: {
                Authorization: 'Bearer AbCdEf123456'
            }
        }
    }
```

Since you are interested in setting an Authorization token, you can access `$http.defaults.headers` directly and set the required headers.

You may also use a request interceptor. For instance:

``` js
$http.interceptors.push({
    request: function(config) {
        config.headers.Authorization = 'Bearer AbCdEf123456';
        return config;
    }
});
```

**Comment by Billybob** [comment]
Each user has a token !
In my case, i have to use a request interceptor

thank you for your availability
